set(_CATKIN_CURRENT_PACKAGE "multi_robot_scenario")
set(multi_robot_scenario_VERSION "0.0.0")
set(multi_robot_scenario_MAINTAINER "reinis <reinis@todo.todo>")
set(multi_robot_scenario_PACKAGE_FORMAT "2")
set(multi_robot_scenario_BUILD_DEPENDS "xacro")
set(multi_robot_scenario_BUILD_EXPORT_DEPENDS "xacro")
set(multi_robot_scenario_BUILDTOOL_DEPENDS "catkin")
set(multi_robot_scenario_BUILDTOOL_EXPORT_DEPENDS )
set(multi_robot_scenario_EXEC_DEPENDS "xacro")
set(multi_robot_scenario_RUN_DEPENDS "xacro")
set(multi_robot_scenario_TEST_DEPENDS )
set(multi_robot_scenario_DOC_DEPENDS )
set(multi_robot_scenario_URL_WEBSITE "")
set(multi_robot_scenario_URL_BUGTRACKER "")
set(multi_robot_scenario_URL_REPOSITORY "")
set(multi_robot_scenario_DEPRECATED "")